name: FastAPI CI/CD

on:
  push:
    branches: 
      - main 

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11


      - name: Install Python Virtual ENV
        run: pip3 install virtualenv


      - name: Activate Virtual ENV
        run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt


      - name: Making Zip File
        run: (cd lib; zip lambda_function.zip -r .) && zip lambda_function.zip -u main.py && zip lambda_function.zip -ur app


      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda_function
          path: lambda_function.zip


  # CD:
  #   runs-on: ubuntu-latest
  #   needs: [CI]
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   steps:
  #     - name: Install AWS CLI
  #       uses: unfor19/install-aws-cli-action@v1
  #       with:
  #         version: 1
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


  #     - name: Download Lambda app.zip
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: app


  #     - name: Upload To S3
  #       run: aws s3 cp app.zip s3://${{ secrets.AWS_BUCKET_NAME }}/app.zip
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


  #     - name: Deploy New Lambda
  #       run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.AWS_BUCKET_NAME }} --s3-key app.zip
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
